# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-20 22:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_question_is_archive'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('name', 'id'), 'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.AddField(
            model_name='question',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='question',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='questions', to='categories.Category', verbose_name="Question's categories"),
        ),
        migrations.AlterField(
            model_name='question',
            name='is_archive',
            field=models.BooleanField(default=False, verbose_name='Question in archive'),
        ),
        migrations.AlterField(
            model_name='question',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Question name'),
        ),
    ]
