# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-03 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0002_remove_answer_question'),
        ('questions', '0007_question_answers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answers',
        ),
        migrations.AddField(
            model_name='question',
            name='answers',
            field=models.ManyToManyField(blank=True, related_name='answers', to='answers.Answer', verbose_name="Question's answers"),
        ),
    ]
