# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-12 18:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0002_remove_answer_question'),
        ('questions', '0008_auto_20180603_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answers',
        ),
        migrations.AddField(
            model_name='question',
            name='answers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='answers.Answer', verbose_name="Question's answers"),
        ),
    ]
