# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-12 18:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_remove_question_answers'),
        ('answers', '0002_remove_answer_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='questions.Question', verbose_name="Answer's question"),
            preserve_default=False,
        ),
    ]
